### ISSUE TITLE
Probleme with your days cross weeks conditions

### ISSUE THREAD

**Issue by Grome13** [theukedge/shortcodes-to-show-or-hide-content#11]
I use your module on a wordpress website and i need to create a condition which cross the week.
I had a probleme with it and after having read your code it seems that there is an error in your shortcodes.php at lines 174, 331 and 496.

I think the condition should be 
if( $onwday < $todaysday || $offwday > $todaysday ) 
and not 
if( $onwday < $todaysday || $offwday < $todaysday )

Talk to you soon about this.

Jérôme

**Comment by theukedge** [comment]
You're absolutely right Jérôme. Thanks for pointing this out!
