### ISSUE TITLE
Huge space on page above weekly repeat code

### ISSUE THREAD

**Issue by Webgoddess007** [theukedge/shortcodes-to-show-or-hide-content#13]
I tried this code and it works but it leaves a huge space above the text. Any ideas as to why I can't get rid of the space? There are <hr> tags on the headlines which I tried removing but that didn't do anything. Here is my code:

[time-restrict-repeat type="weekly" onday="Monday" offday="Monday" ontime="00:00:00" offtime="23:59:00"]
Happy Monday

Beer and a Burger Special $10
Live Juke Box Karaoke 7:30 pm with Dan Renken
Lunch Specials $6,95
Happy Hour 11am till 7pm with $2 OFF APP's 4pm until 6pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Tuesday" offday="Tuesday" ontime="00:00:00" offtime="23:59:00"]
Two 4 Tuesday

Two for One Appetizers from 4pm All night
Happy Hour 11am till 7pm
Dart Grab Bag 7pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Wednesday" offday="Wednesday" ontime="00:00:00" offtime="23:59:00"]
Happy Hump Day from Tim Finnegans

Tonight we have Pub Quiz at 8pm
$5 Martinis and half off our bowls of garlic, white wine,herb steamed Mussels
Win Prizes and bragging rights
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Thursday" offday="Thursday" ontime="00:00:00" offtime="23:59:00"]
Singer Song Writers Night

Live music at the pub with feature singer/songwriters
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Friday" offday="Friday" ontime="00:00:00" offtime="23:59:00"]
TGIF

Live Music Tonight at 8:30pm
$9.95 Fish n Chips
Happy our 11am till 7pm with $2 OFF Appetizers 4pm - 6pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Saturday" offday="Saturday" ontime="00:00:00" offtime="23:59:00"]
Saturday Irish Breakfast Brunch

Mimosa’s and Bloody Mary’s
Served Saturday and Sunday 11am – 3pm
Live Music Tonight at 8 - 11pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Sunday" offday="Sunday" ontime="00:00:00" offtime="23:59:00"]
Sunday Irish Breakfast Brunch

Mimosa’s and Bloody Mary’s
$4 or unlimited $15
Served Saturday and Sunday 11am – 3pm
NFL Football Specials

[/time-restrict-repeat]

**Comment by theukedge** [comment]
Can you send a link to where this code is so that I can check it out? Make sure to butt the first HTML or character immediately after the opening shortcode (putting it on a new line may add a blank paragraph)

**Comment by Webgoddess007** [comment]
i removed all of the html inside the shortcode tags and the space is gone.

**Comment by theukedge** [comment]
There was very possibly a style on one of your HTML tags, like a margin-top being applied to h3 elements
