### ISSUE TITLE
Differing Business Hours

### ISSUE THREAD

**Issue by thomasmattias** [theukedge/shortcodes-to-show-or-hide-content#22]
Really like the Wordpress plugin! Do have a question though. What if you have a business week starting monday and ending on friday but one or more days have different opening/closing times. 

Right now the daily attribute doesn't allow for deviating business hours (or I missed something).

I tried this:
-----

[time-restrict-repeat type="daily" ontime="08:00:00" offtime="20:00:00"]
[time-restrict-repeat-2 type="weekly" onday="Monday" offday="tuesday"]
We are currently open
[/time-restrict-repeat-2]
[/time-restrict-repeat]

[time-restrict-repeat type="daily" ontime="08:30:00" offtime="17:30:00"]
[time-restrict-repeat-2 type="weekly" onday="tuesday" offday="friday"]
We are currently open
[/time-restrict-repeat-2]
[/time-restrict-repeat]

-----

Would be cool if there was an option like this (bit long but would do the trick):
-----

[time-restrict-repeat type="Monday" ontime="08:00:00" offtime="20:00:00"] 
[time-restrict-repeat-2 type="Tuesday" ontime="08:30:00" offtime="17:30:00"] 
[time-restrict-repeat-3 type="Wednesday" ontime="08:30:00" offtime="17:30:00"]
[time-restrict-repeat-4 type="Thursday" ontime="08:30:00" offtime="17:30:00"]
[time-restrict-repeat-5 type="Friday" ontime="08:30:00" offtime="16:30:00"]
We are selling T-Rex meat hotdogs right now!
[/time-restrict-repeat-5]
[/time-restrict-repeat-4]
[/time-restrict-repeat-3]
[/time-restrict-repeat-2]
[/time-restrict-repeat]

-----

Or this to keep it cleaner:
-----

[time-restrict-repeat type="Monday" ontime="08:00:00" offtime="20:00:00"] 
[time-restrict-repeat-5 type="Tuesday > Friday" ontime="08:30:00" offtime="17:30:00"]
We are selling mermaid costumes at this moment!
[/time-restrict-repeat-2]
[/time-restrict-repeat]

**Comment by theukedge** [comment]
Your first attempt was closest:

```
[time-restrict-repeat type="daily" ontime="08:00:00" offtime="20:00:00"]
[time-restrict-repeat-2 type="weekly" onday="Monday" offday="Monday"]
We are currently open
[/time-restrict-repeat-2]
[/time-restrict-repeat][time-restrict-repeat type="daily" ontime="08:30:00" offtime="17:30:00"]
[time-restrict-repeat-2 type="weekly" onday="Tuesday" offday="Thursday"]
We are currently open
[/time-restrict-repeat-2]
[/time-restrict-repeat][time-restrict-repeat type="daily" ontime="08:30:00" offtime="16:30:00"]
[time-restrict-repeat-2 type="weekly" onday="Friday" offday="Friday"]
We are currently open
[/time-restrict-repeat-2]
[/time-restrict-repeat]
```
