### ISSUE TITLE
Dates + Days

### ISSUE THREAD

**Issue by anetk** [theukedge/shortcodes-to-show-or-hide-content#23]
Hi there,

would something like this work?
[time-restrict-repeat type="weekly" onday="Tuesday" offday="Tuesday" on="2016-11-24" on="2016-11-29"]

Or shall I add off dates as well?

**Comment by vladootz** [comment]
Hi @anetk,
I see in the code that there is no use for on="" and the alternative (ondate="") is only used on anually and monthly repeats, no weekly.

**Comment by theukedge** [comment]
You can set one-time schedules using the `on` and `off` attributes, [which are still there](https://github.com/theukedge/shortcodes-to-show-or-hide-content/blob/master/includes/shortcodes.php#L29-L30). Examples of this can be found on [the plugin description](https://wordpress.org/plugins/shortcodes-to-show-or-hide-content/) page.
