### ISSUE TITLE
Adding an image to shortcode 

### ISSUE THREAD

**Issue by MidlandsMetalheads** [theukedge/shortcodes-to-show-or-hide-content#29]
ALRIGHT GUYS
I AM TRYING TO ADD AN IMAGE FROM MY MEDIA LIBRARY ON MY WORDPRESS SITE, AND ADD IT TO THE SHORTCODE YOU PROVIDE ON YOUR PLUGIN PAGE 

[TIME-RESTRICT-REPEAT TYPE="DAILY" ONTIME="23:00:00" OFFTIME="23:59:00"]IMAGE HERE?[/TIME-RESTRICT-REPEAT]

I AM USING SITEORIGINS PAGE BUILDER AND USING SHORTCODE ULTIMATE WIDGET 

ANY HELP WOULD BE AMAZING

BEST
ADAM

**Comment by theukedge** [comment]
Hi Adam,

You simply need to add the code for the image between the opening and closing `time-restrict-repeat` shortcode tags. If it's simply HTML, it'll take the form `<img src="" alt="" width="" height= "" />` or if you're using a pagebuilder, they may provide a shortcode for the image instead. Either way, just insert the image into your content and then put the `time-restrict-repeat` shortcode tags around it.

**Comment by MidlandsMetalheads** [comment]
Hi Dave,
can I ask is JavaScript needed for this plugin.
for some reason I can't get it to work

Best
Adam Till
Owner / DJ Manager
Midlands Metalheads Radio
Email: adamtill@midlandsmetalheads.com
Web: www.midlandsmetalheads.com<http://%20www.midlandsmetalheads.com>
Personal Bio: http://goo.gl/24hD0x

**Comment by theukedge** [comment]
Nope, no JS required whatsoever
