### ISSUE TITLE
Set current time to test your content

### ISSUE THREAD

**Issue by stephenjbell** [theukedge/shortcodes-to-show-or-hide-content#30]
Maybe I'm missing something, but there doesn't seem to be any way to test whether or not your code is working except to wait until the actual time that things are supposed to show/hide. I'm working on a restaurant website where the schedule varies from day to day, and it's complex enough that it would be nice to know that everything is working as planned.

It would be great if there were a way to set the time before your content loads, like:

`[time-restrict-test current="2017/09/10 18:00:00"]`

**Comment by theukedge** [comment]
Hi Stephen,

I think a better approach than creating a new shortcode that allows for testing is to either use the built-in "Preview Changes" option in WordPress, or simply to use the shortcodes on a private page (which is by its very nature, not visible to the public) for testing purposes.

Is there any reason something like that wouldn't work?

**Comment by stephenjbell** [comment]
I don't think I explained myself very well. What I'm asking for is a way to test the content for a specific time that isn't the current one. I want a way to tell the page "show me this content as it will display on Thursday, August 3 at 10:03pm." Being able to jump around in time would let me see if my complicated shortcodes are doing what I think they should do.
