### ISSUE TITLE
Idea - Ability to set at page level

### ISSUE THREAD

**Issue by akmiecik** [theukedge/shortcodes-to-show-or-hide-content#31]
In addition to setting date/time for content, is it feasible to do it at the page level?

**Comment by theukedge** [comment]
It isn't currently and isn't likely to be something to be incorporated into this plugin. In terms of publishing content at a set time, that's built-in to WordPress, and there's other plugins that can "unpublish" content at a given date/time ([e.g.](https://wordpress.org/plugins/archived-post-status/))
