### ISSUE TITLE
Short Code Content

### ISSUE THREAD

**Issue by vem4kids** [theukedge/shortcodes-to-show-or-hide-content#33]
Is this only to show/hide text?  I'd really love to be able to control short code content.  For instance, I'm using a form but I want the form to cut off on an expiration date.

**Comment by theukedge** [comment]
Nope, you can also use it with shortcodes. Put a shortcode inside this shortcode and it will respond to the show/hide rules, just like text would.

**Comment by vem4kids** [comment]
Thank you for your response.  I’m sorry but this is not working for me.  

 

This is how I’ve used the code:

 

[time-restrict off="2017-09-01"][Form id="17"][/time-restrict] [time-restrict on="2017-12-12"] Registration for this day care day has closed. Please contact the school office to inquire about available openings. 757-337-0343 or info@deepcreekacademy.com [/time-restrict]

 

When the restriction is on, it works just fine.  When the restriction is off, the form that I need does not show up.

 

Any ideas?

**Comment by vem4kids** [comment]
Thank you!  I’m all better now.  I misunderstood which code did what and when.
