### ISSUE TITLE
Content not showing on mobile

### ISSUE THREAD

**Issue by stevenspeegle** [theukedge/shortcodes-to-show-or-hide-content#37]
Hello, 
   I've been using your plugin for a while now and have just recently noticed that the content I show and hide is only doing so on the desktop. It stopped working on mobile. Can you help me figure out what's going on? the website is http://www.885jfm.com

**Comment by theukedge** [comment]
-- Please reply above this line --

Hello Theukedge/shortcodes-To-Show-Or-Hide-Con,

We've received your email and will respond as soon as we can.

We usually respond within one business day and our normal business
hours are Monday-Friday, 7am-4pm Pacific time.

If this is an urgent matter (your website is down, or you need to
restore from a backup), you can respond with the word "urgent", and
I'll review your message as soon as possible and determine the best
course of action.

Thanks

**Comment by theukedge** [comment]
Being that the plugin hasn't changed, this must be down to something else on your website. I have your email and suggest that we work through it there.
