### ISSUE TITLE
Weekly onday offday not working

### ISSUE THREAD

**Issue by lundstrategy** [theukedge/shortcodes-to-show-or-hide-content#38]
offday=Monday" has not worked consistently? Not sure if I need to update WordPress settings? 

[time-restrict-repeat type="weekly" onday="Sunday" offday="Monday"]
Content Area
[/time-restrict-repeat]

Thanks for your help.

**Comment by theukedge** [comment]
-- Please reply above this line --

Hello Theukedge/shortcodes-To-Show-Or-Hide-Con,

We've received your email and will respond as soon as we can.

We usually respond within one business day and our normal business
hours are Monday-Friday, 7am-4pm Pacific time.

If this is an urgent matter (your website is down, or you need to
restore from a backup), you can respond with the word "urgent", and
I'll review your message as soon as possible and determine the best
course of action.

Thanks

**Comment by lundstrategy** [comment]
I’d like to just show it on Sunday. And go away Monday through Saturday. Do I just have it say onday=“Sunday”?

Larry

**Comment by theukedge** [comment]
In that case, your offday should be Sunday as well. The default off time is 23:59:59, so if you set your offday to Sunday, it will turn off at 23:59:59, just before Monday starts.

**Comment by lundstrategy** [comment]
Awesome. Thank you! I can make a donation for your time. Just send a link!

**Comment by theukedge** [comment]
That's very kind of you to offer. You can do so here: https://www.theukedge.com/donate/

Thanks!

**Comment by lundstrategy** [comment]
Will do! Thank you.

Larry
