### ISSUE TITLE
Shortcode only works when user is admin and is logged in

### ISSUE THREAD

**Issue by fhervazquez** [theukedge/shortcodes-to-show-or-hide-content#39]
I noticed that the condition only works when the user/visitor is logged in. I am using the shortcode here: https://weekendmaids.net/san-diego-maid-service-house-cleaning/

Depending on the time It should display a button with a given URL, during office hours (8am to 5pm) the shortcode should display a red button with a URL to the contact page, after 5pm until 7:59am it should display a button with a link to a form...

**Comment by theukedge** [comment]
You are almost certainly looking at an issue of caching, since this plugin doesn't even consider user permissions.
