### ISSUE TITLE
Weekly scheduled content on the same page

### ISSUE THREAD

**Issue by Shonari** [theukedge/shortcodes-to-show-or-hide-content#7]
Hello

Can the plugin handle usage one the same page as described below?

Also, do I have to set the 'offday' or will it automatically turn off once the day is past

[time-restrict-repeat type="weekly" onday="Monday"]
Monday content
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Tuesday"]
Tuesday content
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Wednesday"]
Wednesday content
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Thursday"]
Thursday content
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Friday"]
Friday content
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Saturday"]
Saturday content
[/time-restrict-repeat]

Thanks for building such a great plugin!

**Comment by theukedge** [comment]
You need to set the offday, but this will absolutely work.

**Comment by Shonari** [comment]
Thanks for your reply

I did as the description says but three days out of the week is showing up instead of only one: http://kirkmarket.ky/daily-menu-2/

My time/date setting are ok via the settings page and its the same code snippet i used for money (just changed the days)

**Comment by Shonari** [comment]
Here is the code:

[time-restrict-repeat type="weekly" onday="Sunday" offday="Tuesday"]

<strong>MONDAY MENU</strong>

[tabs tab1="LUNCH" tab2="MEDITERRANEAN" tab3="DINNER" tab4="SANDWICHES"] [tab] Kirk Market's hot bar buffet is LEGENDARY, with a variety of hot nourishing entrees and vegetables. Plus Soup of the Day and a variety of wings and ribs fresh from our own smoker. &nbsp;

LUNCH MENU

Baked Chicken
Oxtail
Fish Portuguese
Grilled Blackened Pork Chops with Onion &amp; Peppers
Roast Chicken with Mango Chutney
White Rice
Rice &amp; Beans
Boiled Cheese Potato
Pasta with Salmon in Cream Sauce
Smoked Beef Brisket
Jerk Pork
Chili Beans
Steamed Vegetables

TODAY’S SOUPS:

Beef &amp; Barley Soup
Cream of Pumpkin Soup

[/tab]

[tab] Fancy a walk on the light side? Everyday our chef makes a fresh selection from our over 70 varieties of salads, cheeses and cold meats, priced competitively by the pound. Todays will include: &nbsp;

Mixed Greens Salad
Spinach Salad
Caesar Salad Pasta with Chicken
Pasta with Salmon
Grilled Beef Steak
Grilled Spicy Beef Steak
Grilled Salmon with Seaweed Salad
Grilled Chicken with basil Sundried Tomato
Poached Shrimp Salad
Avocado Salad
Oriental BBQ Pork Tenderloin
Grilled Asparagus
Grilled Corn Salad
Quinoa Salad

[/tab]

[tab] After a hard day’s work take a night off cooking by selecting from the hot bar. &nbsp;

TODAY’S HOT BAR DINNER MENU

Baked Chicken
Mediterranean Chicken Breast
Roast Leg of Lamb with Red Wine &amp; Rosemary Reduction
Cajun Style Mahi
Grilled Bratwurst Sausage with Onion Gravy
New Orleans Style Jambalaya
Rustic Potato Salad
Mediterranean Pasta with Chicken Sausage
Shepherds Pie
Baked Chicken
Curry Chicken
Fish &amp; Chips
Peppered Steak
Turkey Casserole

[/tab]

[tab] We make sandwiches large ($6.50) or small ($4.50) to your special order from a variety of fresh breads, cheeses and cold cuts and our special dressings. We also offer a daily special.
[content_half]
<p style="text-align: center;"><b>ORDER A CUSTOM SANDWICH ONLINE</b>
[product id="13172" sku=""]
[/content_half]
[content_half id="last"]
<b>ORDER TODAY'S SANDWICH SPECIAL</b></p>
<p style="text-align: center;">[product id="12783" sku=""]&nbsp;</p>
[/content_half]
[/tab] [/tabs]
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Tuesday" offday="Wednesday"]

<strong>TUESDAY MENU</strong>

[tabs tab1="LUNCH" tab2="MEDITERRANEAN" tab3="DINNER" tab4="SANDWICHES"] [tab] Kirk Market's hot bar buffet is LEGENDARY, with a variety of hot nourishing entrees and vegetables. Plus Soup of the Day and a variety of wings and ribs fresh from our own smoker. &nbsp;

LUNCH MENU

Baked Chicken
Oxtail
Grilled Blackened Snapper with Onion &amp; Peppers
Carne Asada
Curry Chicken
White Rice
Gungo Rice
Roast Potato
Stir Fry Tofu
Smoked Beef Brisket
Steamed Vegetables

TODAY’S SOUPS:

Roast Butternut Squash Soup
Beef Soup

[/tab]

[tab] Fancy a walk on the light side? Everyday our chef makes a fresh selection from our over 70 varieties of salads, cheeses and cold meats, priced competitively by the pound. Todays will include: &nbsp;

Mixed Greens Salad
Spinach Salad
Caesar Salad Pasta with Chicken
Pasta with Salmon
Grilled Beef Steak
Grilled Beef Steak with Chimichuri Sauce
Grilled Salmon with Sweet Ancho Chili Sauce
Grilled Spicy Shrimp
Grilled Herb marinade Chicken
Grilled Blackened Turkey
Avocado Salad
Chick Pea Salad
Cous Cous
Tomato Mozzarella

[/tab]

[tab] After a hard day’s work take a night off cooking by selecting from the hot bar. &nbsp;

TODAY’S HOT BAR DINNER MENU

Baked Chicken
Salmon and Shrimp Fried Rice
Schezuan Spicy Beef
Fried Fish with Sweet Chili Garlic Sauce
Chicken Chop Suey
Stir Fry Tofu
Sweet &amp; Sour Chicken
Sriracha Fried Wings
Grilled Snapper with Cucumber &amp; Tomato Salsa
Ground Beef with Veggie
Thai Curry Beef
Roast Pork with Plum Sauce

[/tab]

[tab] We make sandwiches large ($6.50) or small ($4.50) to your special order from a variety of fresh breads, cheeses and cold cuts and our special dressings. We also offer a daily special.
[content_half]
<p style="text-align: center;"><b>ORDER A CUSTOM SANDWICH ONLINE</b>
[product id="13172" sku=""]
[/content_half]
[content_half id="last"]
<b>ORDER TODAY'S SANDWICH SPECIAL</b></p>
<p style="text-align: center;">[product id="12785" sku=""]&nbsp;</p>
[/content_half]
[/tab] [/tabs]
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Wednesday" offday="Thursday"]

<strong>WEDNESDAY MENU</strong>

[tabs tab1="LUNCH" tab2="MEDITERRANEAN" tab3="DINNER" tab4="SANDWICHES"] [tab] Kirk Market's hot bar buffet is LEGENDARY, with a variety of hot nourishing entrees and vegetables. Plus Soup of the Day and a variety of wings and ribs fresh from our own smoker. &nbsp;

LUNCH MENU

Baked Chicken
Oxtail
Breaded Grouper Salisbury Steak with Onion &amp; Gravy
Stew Chicken
White Rice
Pilaf Rice
Mashed Potato
Black Bean Stew
Smoked Beef Brisket
Pasta with Salmon in Tomato Cream Sauce
Steamed Vegetables

TODAY’S SOUPS:

Cream of Tomato Soup
Chicken Soup

[/tab]

[tab] Fancy a walk on the light side? Everyday our chef makes a fresh selection from our over 70 varieties of salads, cheeses and cold meats, priced competitively by the pound. Todays will include: &nbsp;

Mixed Greens Salad
Spinach Salad
Caesar Salad Pasta with Chicken
Pasta with Salmon
Grilled Beef Steak
Grilled Spicy Beef Steak
Grilled Paprika Shrimp
Grilled Salmon with Balsamic Glaze
Grilled Chicken with Basil Pesto
Grilled Lamb Cutlet
Avocado Salad
Artichoke Salad
Tuna Tataki
Oriental BBQ Baby Back Ribs

[/tab]

[tab] After a hard day’s work take a night off cooking by selecting from the hot bar. &nbsp;

TODAY’S HOT BAR DINNER MENU

Baked Chicken
Carne Asada
Fried Chalets with Onion &amp; Cassava
Arroz Con Pollo
Nacho Chips with Cheese Sauce
Fresh Tortillas
Ground Beef
Fried Plantain
Fried Eggs
Beef Enchiladas with Cottage Cheese
Chicken Burritos
Grilled Marinade Cuban Pork
Curry Beef
Pasta with Prosciutto in Cream Sauce

[/tab]

[tab] We make sandwiches large ($6.50) or small ($4.50) to your special order from a variety of fresh breads, cheeses and cold cuts and our special dressings. We also offer a daily special.
[content_half]
<p style="text-align: center;"><b>ORDER A CUSTOM SANDWICH ONLINE</b>
[product id="13172" sku=""]
[/content_half]
[content_half id="last"]
<b>ORDER TODAY'S SANDWICH SPECIAL</b></p>
<p style="text-align: center;">[product id="12787" sku=""]&nbsp;</p>
[/content_half]
[/tab] [/tabs]
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Thursday" offday="Friday"]

<strong>THURSDAY MENU</strong>

[tabs tab1="LUNCH" tab2="MEDITERRANEAN" tab3="DINNER" tab4="SANDWICHES"] [tab] Kirk Market's hot bar buffet is LEGENDARY, with a variety of hot nourishing entrees and vegetables. Plus Soup of the Day and a variety of wings and ribs fresh from our own smoker. &nbsp;

LUNCH MENU

Baked Chicken
Oxtail
Roast Turkey with Gravy
Grilled Pork Chops with Creole Sauce
Teriyaki Spicy Beef
Panfried Mahi with Lemon Capers Butter
White Rice
Rice &amp; Beans
Mashed Potato
Macaroni &amp; Cheese
Smoked Beef Brisket
Steamed Vegetables

TODAY’S SOUPS:

Thai Chicken Soup
Lima Bean Soup

[/tab]

[tab] Fancy a walk on the light side? Everyday our chef makes a fresh selection from our over 70 varieties of salads, cheeses and cold meats, priced competitively by the pound. Todays will include: &nbsp;

Mixed Greens Salad
Spinach Salad
Caesar Salad Pasta with Chicken
Pasta with Salmon
Grilled Beef Steak
Beef &amp; Broccoli
Grilled Blackened Salmon
Grilled Shrimp with Sweet &amp; Sour Sauce
Grilled Paprika Chicken
Lamb Shish Kebab
Brown Rice Salad
Tomato Mozzarella
Edamame Salad
Mango with Cucumber Salad

[/tab]

[tab] After a hard day’s work take a night off cooking by selecting from the hot bar. &nbsp;

TODAY’S HOT BAR DINNER MENU

Baked Chicken
Osso Buco
Meat Lasagna
Fried Calamari
Sicilian Stuffer Peppers
Fresh Meatballs in Tomato Sauce
Penne Pasta with Salmon in Fennel Cream Sauce
Scalloped Potato
Panfried Grouper with olive Tapenade
Ratatouille
Beef Pot Pie
Grilled Pork Chops with Herb Butter

[/tab]

[tab] We make sandwiches large ($6.50) or small ($4.50) to your special order from a variety of fresh breads, cheeses and cold cuts and our special dressings. We also offer a daily special.
[content_half]
<p style="text-align: center;"><b>ORDER A CUSTOM SANDWICH ONLINE</b>
[product id="13172" sku=""]
[/content_half]
[content_half id="last"]
<b>ORDER TODAY'S SANDWICH SPECIAL</b></p>
<p style="text-align: center;">[product id="12781" sku=""]&nbsp;</p>
[/content_half]
[/tab] [/tabs]
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Friday" offday="Saturday"]

<b>FRIDAY&nbsp;MENU</b>

[tabs tab1="LUNCH" tab2="MEDITERRANEAN" tab3="DINNER" tab4="SANDWICHES"] [tab] Kirk Market's hot bar buffet is LEGENDARY, with a variety of hot nourishing entrees and vegetables. Plus Soup of the Day and a variety of wings and ribs fresh from our own smoker. &nbsp;

LUNCH MENU

Baked Chicken
Oxtail
Jerk Pork
Thai Chicken Curry
White Rice
Rice &amp; Beans
Roast Potato
Lentil Vegetable Stew
Smoked Beef Brisket
Pasta with Prosciutto in Tomato Cream Sauce
Roast Beef with mushroom Sauce
Grilled Snapper with Mango Salsa
Steamed Vegetables

TODAY’S SOUPS:

Black Bean Soup
Beef Soup

[/tab]

[tab] Fancy a walk on the light side? Everyday our chef makes a fresh selection from our over 70 varieties of salads, cheeses and cold meats, priced competitively by the pound. Todays will include: &nbsp;

Mixed Greens Salad
Spinach Salad
Caesar Salad Pasta with Chicken
Pasta with Salmon
Grilled Beef Steak
Grilled Spicy Beef Steak
Grilled Salmon with lemon Vinaigrette
Grilled Garlic Shrimp
Grilled Blackened Chicken
Pan Seared Duck with Oriental BBQ Sauce
Avocado Salad
Assorted Cauliflower Salad
Grilled Corn Salad
Tuna Tartar

[/tab]

[tab] After a hard day’s work take a night off cooking by selecting from the hot bar. &nbsp;

TODAY’S HOT BAR DINNER MENU

Baked Chicken
Chicken Tikka Mahkani
Vegetable Pilaf Rice
Fish Caldine
Pork Vindaloo
Vegetable Masala
Green Beef Masala
Potato Baji
Naan Bread
Fried Curried Spicy Wings
Grilled Cajun Snapper with Creole Sauce
Dal Fry
Stir Fry Tofu
Chicken Pot Pie
Mashed Potatoes

[/tab]

[tab] We make sandwiches large ($6.50) or small ($4.50) to your special order from a variety of fresh breads, cheeses and cold cuts and our special dressings. We also offer a daily special.
[content_half]
<p style="text-align: center;"><b>ORDER A CUSTOM SANDWICH ONLINE</b>
[product id="13172" sku=""]
[/content_half]
[content_half id="last"]
<b>ORDER TODAY'S SANDWICH SPECIAL</b></p>
<p style="text-align: center;">[product id="12789" sku=""]&nbsp;</p>
[/content_half]
[/tab] [/tabs]
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Saturday" offday="Sunday"]

<b>SATURDAY MENU</b>

[tabs tab1="LUNCH" tab2="MEDITERRANEAN" tab3="DINNER" tab4="SANDWICHES"] [tab] Kirk Market's hot bar buffet is LEGENDARY, with a variety of hot nourishing entrees and vegetables. Plus Soup of the Day and a variety of wings and ribs fresh from our own smoker. &nbsp;

LUNCH MENU

Baked Chicken
Oxtail
Curry Goat
Jerk Pork
Breaded Grouper
White Rice
Rice &amp; Beans
Boiled Parsley Potato
Penne Alforno
Smoked Beef Brisket
Steamed Vegetables

TODAY’S SOUPS:

Conch Soup
Beef Soup

[/tab]

[tab] Fancy a walk on the light side? Everyday our chef makes a fresh selection from our over 70 varieties of salads, cheeses and cold meats, priced competitively by the pound. Todays will include: &nbsp;

Mixed Greens Salad
Spinach Salad
Caesar Salad Pasta with Chicken
Pasta with Salmon
Grilled Beef Steak
Grilled Spicy Beef Steak
Grilled Herb Marinade Chciken
Grilled Salmon with Roasted Bell Pepper Coulis
Grilled Shrimp Scampii
Avocado Salad
Fish Cake
Grilled Asparagus
Chick Pea Salad
Asian Slaw

[/tab]

[tab] After a hard day’s work take a night off cooking by selecting from the hot bar. &nbsp;

TODAY’S HOT BAR DINNER MENU

Baked Chicken
Jerk pork
Curry Chicken
Snapper Escovitch
Caribbean Peppered Steak
BBQ Chicken
Fried Festival
Poached Snapper with Coconut Milk
Chicken Fricassie
Panfried Grouper with Lemon
Cauliflower with Chick Pea Curry
Double Baked Potato
Oriental Chicken Noodles

[/tab]

[tab] We make sandwiches large ($6.50) or small ($4.50) to your special order from a variety of fresh breads, cheeses and cold cuts and our special dressings. We also offer a daily special.
[content_half]
<p style="text-align: center;"><b>ORDER A CUSTOM SANDWICH ONLINE</b>
[product id="13172" sku=""]
[/content_half]
[content_half id="last"]
<b>ORDER TODAY'S SANDWICH SPECIAL</b></p>
<p style="text-align: center;">[/content_half]</p>
[/tab] [/tabs]
[/time-restrict-repeat]

**Comment by theukedge** [comment]
That's because your onday and offday need to match the menu that you want to show. For example, for Tuseday's menu, the onday and offday should also be Tuesday (this means the code shows up at 00:00 on Tuesday and turns off at 23:59 on Tuesday).

**Comment by Shonari** [comment]
Brilliant! Thanks!

**Comment by Webgoddess007** [comment]
I tried this code and it works but it leaves a huge space above the text. Any ideas as to why I can't get rid of the space? Here is my code:


[time-restrict-repeat type="weekly" onday="Monday" offday="Monday" ontime="00:00:00" offtime="23:59:00"]
<h3 style="color: #ff6600; text-align: center;">Happy Monday</h3>
Beer and a Burger Special $10
Live Juke Box Karaoke 7:30 pm with Dan Renken
Lunch Specials $6,95
Happy Hour 11am till 7pm with $2 OFF APP's 4pm until 6pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Tuesday" offday="Tuesday" ontime="00:00:00" offtime="23:59:00"]
<h3 style="color: #ff6600; text-align: center;">Two 4 Tuesday</h3>
Two for One Appetizers from 4pm All night
Happy Hour 11am till 7pm
Dart Grab Bag 7pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Wednesday" offday="Wednesday" ontime="00:00:00" offtime="23:59:00"]
<h3 style="color: #ff6600; text-align: center;">Happy Hump Day from Tim Finnegans</h3>
Tonight we have Pub Quiz at 8pm
$5 Martinis and half off our bowls of garlic, white wine,herb steamed Mussels
Win Prizes and bragging rights
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Thursday" offday="Thursday" ontime="00:00:00" offtime="23:59:00"]
<h3 style="color: #ff6600; text-align: center;">Singer Song Writers Night</h3>
Live music at the pub with feature singer/songwriters
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Friday" offday="Friday" ontime="00:00:00" offtime="23:59:00"]
<h3 style="color: #ff6600; text-align: center;">TGIF</h3>
Live Music Tonight at 8:30pm
$9.95 Fish n Chips
Happy our 11am till 7pm with $2 OFF Appetizers 4pm - 6pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Saturday" offday="Saturday" ontime="00:00:00" offtime="23:59:00"]
<h3 style="color: #ff6600; text-align: center;">Saturday Irish Breakfast Brunch</h3>
Mimosa’s and Bloody Mary’s
Served Saturday and Sunday 11am – 3pm
Live Music Tonight at 8 - 11pm
[/time-restrict-repeat]

[time-restrict-repeat type="weekly" onday="Sunday" offday="Sunday" ontime="00:00:00" offtime="23:59:00"]
<h3 style="color: #ff6600; text-align: center;">Sunday Irish Breakfast Brunch</h3>
Mimosa’s and Bloody Mary’s
$4 or unlimited $15
Served Saturday and Sunday 11am – 3pm

<h3>NFL Football Specials</h3>
[/time-restrict-repeat]</div>
